import { Inter } from 'next/font/google'
import './globals.css'
import { AudioTextProvider } from './contexts/AudioTextContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <AudioTextProvider>
      <body className={inter.className}>{children}</body>
    </AudioTextProvider>
    </html>
  )
}
