import { Inter } from 'next/font/google'
import './globals.css'
import { AudioTextProvider } from './contexts/AudioTextContext'
import { PresentationContextProvider } from './contexts/PresentationContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ESL Presentation Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AudioTextProvider>
      <PresentationContextProvider>
        <body className={inter.className}>{children}</body>
      </PresentationContextProvider>
      </AudioTextProvider>
    </html>
  )
}
